// Code generated by go:generate; DO NOT EDIT.

// Generated with command: go generate
// (from the project root)

package modules

import (
	_ "github.com/GoMudEngine/GoMud/modules/cleanup"
	_ "github.com/GoMudEngine/GoMud/modules/follow"
	_ "github.com/GoMudEngine/GoMud/modules/gmcp"
	_ "github.com/GoMudEngine/GoMud/modules/webhelp"
)
